service: babite-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-babel-plugin

provider:
  name: aws
  runtime: nodejs10.13.0
  stage: dev
  region: eu-central-1


  custom:
  babelPresets:
    - latest
  # bundle:
  #   sourcemaps: true          # Enable source maps
  #   caching: true             # Enable Webpack caching
  #   stats: false              # Don't print out any Webpack output
  #   linting: true             # Enable linting as a part of the build process
  #   forceInclude:             # Optional list of NPM packages that need to be included
  #     - mysql                   # Only necessary if packages are included dynamically
  #   ignorePackages:           # Ignore building any of the following packages
  #     - hiredis                 # For ex, hiredis needs to be ignored if using redis
  #   fixPackages:              # Include fixes for specific packages
  #     - "formidable@1.x"        # For ex, formidable@1.x doesn't work by default with Webpack
  #   copyFiles:                # Copy any additional files to the generated package
  #     - from: 'public/*'        # Where the files are currently
  #       to: './'                # Where in the package should they go
  #   packager: npm             # Specify a packager, 'npm' or 'yarn'. Defaults to 'npm'.
  #   packagerOptions:          # Run a custom script in the package process
  #     scripts:                  # https://github.com/serverless-heaven/serverless-webpack#custom-scripts
  #       - echo hello > test
